import { CatalogBrowsePayload, ProductItem, ShopCategory } from "@/lib/catalog/types";

const CATEGORY_COPY: CatalogBrowsePayload["categories"] = [
  { slug: "beef", label: "Beef", description: "Prime cuts, steaks, roasts, and grinds." },
  { slug: "pork", label: "Pork", description: "Chops, shoulder, bacon, and house cures." },
  { slug: "chicken", label: "Chicken", description: "Fresh poultry cuts and marinated options." },
  { slug: "sausage", label: "Sausage", description: "House-made links, brats, and patties." },
  { slug: "seafood", label: "Seafood", description: "Fresh fish and shellfish for pickup." },
  { slug: "prepared-foods", label: "Prepared Foods", description: "Ready-to-heat meals and sides." },
  { slug: "bundles", label: "Bundles", description: "Family boxes and grill-ready packs." },
];

const categoryLabelMap = Object.fromEntries(CATEGORY_COPY.map((entry) => [entry.slug, entry.label])) as Record<ShopCategory, string>;

export const mockCatalogProducts: ProductItem[] = [
  {
    id: "item_beef_ribeye",
    slug: "prime-ribeye-steak",
    category: "beef",
    categoryLabel: categoryLabelMap.beef,
    name: "Prime Ribeye Steak",
    shortDescription: "USDA prime ribeye, hand-cut daily with rich marbling.",
    imageUrl: "https://images.unsplash.com/photo-1603048719539-9ecb5ef9b6cb?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["steak", "grill"],
    variations: [{ id: "var_ribeye_12oz", name: "12 oz cut", sku: "BEEF-RIBEYE-12", priceMoney: { amount: 2499, currency: "USD" }, unitName: "each" }],
  },
  {
    id: "item_beef_ground",
    slug: "grass-fed-ground-beef",
    category: "beef",
    categoryLabel: categoryLabelMap.beef,
    name: "Grass-Fed Ground Beef",
    shortDescription: "Lean 85/15 grind from locally raised cattle.",
    imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80",
    tags: ["ground", "meal-prep"],
    variations: [{ id: "var_ground_1lb", name: "1 lb pack", sku: "BEEF-GROUND-1", priceMoney: { amount: 899, currency: "USD" }, unitName: "lb" }],
  },
  {
    id: "item_pork_chop",
    slug: "thick-cut-pork-chops",
    category: "pork",
    categoryLabel: categoryLabelMap.pork,
    name: "Thick-Cut Pork Chops",
    shortDescription: "Bone-in center-cut chops, ideal for pan searing.",
    imageUrl: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=900&q=80",
    tags: ["chops", "weeknight"],
    variations: [{ id: "var_porkchop_2pack", name: "2-pack", sku: "PORK-CHOP-2", priceMoney: { amount: 1299, currency: "USD" }, unitName: "pack" }],
  },
  {
    id: "item_pork_belly",
    slug: "heritage-pork-belly",
    category: "pork",
    categoryLabel: categoryLabelMap.pork,
    name: "Heritage Pork Belly",
    shortDescription: "Skin-on pork belly, perfect for smoking or braising.",
    imageUrl: "https://images.unsplash.com/photo-1529692236671-f1dc1f55fe80?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["smoke", "slow-cook"],
    variations: [{ id: "var_porkbelly_1lb", name: "1 lb slab", sku: "PORK-BELLY-1", priceMoney: { amount: 1099, currency: "USD" }, unitName: "lb" }],
  },
  {
    id: "item_chicken_thigh",
    slug: "air-chilled-chicken-thighs",
    category: "chicken",
    categoryLabel: categoryLabelMap.chicken,
    name: "Air-Chilled Chicken Thighs",
    shortDescription: "Boneless thighs trimmed and ready for marinades.",
    imageUrl: "https://images.unsplash.com/photo-1529692236671-f1dc1f55fe80?auto=format&fit=crop&w=900&q=80",
    tags: ["chicken", "meal-prep"],
    variations: [{ id: "var_chicken_thigh_1lb", name: "1 lb pack", sku: "CHK-THIGH-1", priceMoney: { amount: 699, currency: "USD" }, unitName: "lb" }],
  },
  {
    id: "item_chicken_wings",
    slug: "party-chicken-wings",
    category: "chicken",
    categoryLabel: categoryLabelMap.chicken,
    name: "Party Chicken Wings",
    shortDescription: "Split wings for game day trays and smokers.",
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["party", "grill"],
    variations: [{ id: "var_chicken_wings_2lb", name: "2 lb tray", sku: "CHK-WING-2", priceMoney: { amount: 1499, currency: "USD" }, unitName: "tray" }],
  },
  {
    id: "item_sausage_italian",
    slug: "sweet-italian-sausage",
    category: "sausage",
    categoryLabel: categoryLabelMap.sausage,
    name: "Sweet Italian Sausage",
    shortDescription: "House-ground pork sausage with fennel and garlic.",
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=900&q=80",
    tags: ["house-made", "grill"],
    variations: [{ id: "var_sausage_italian_5", name: "5 links", sku: "SAUS-ITAL-5", priceMoney: { amount: 1399, currency: "USD" }, unitName: "pack" }],
  },
  {
    id: "item_sausage_brat",
    slug: "beer-bratwurst-links",
    category: "sausage",
    categoryLabel: categoryLabelMap.sausage,
    name: "Beer Bratwurst Links",
    shortDescription: "Classic brat links blended with local lager.",
    imageUrl: "https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&w=900&q=80",
    tags: ["house-made", "party"],
    variations: [{ id: "var_sausage_brat_6", name: "6 links", sku: "SAUS-BRAT-6", priceMoney: { amount: 1499, currency: "USD" }, unitName: "pack" }],
  },
  {
    id: "item_seafood_salmon",
    slug: "atlantic-salmon-fillets",
    category: "seafood",
    categoryLabel: categoryLabelMap.seafood,
    name: "Atlantic Salmon Fillets",
    shortDescription: "Fresh center-cut salmon portions, skin-on.",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["seafood", "weeknight"],
    variations: [{ id: "var_salmon_8oz", name: "8 oz fillet", sku: "SEA-SALM-8", priceMoney: { amount: 1299, currency: "USD" }, unitName: "each" }],
  },
  {
    id: "item_seafood_shrimp",
    slug: "jumbo-gulf-shrimp",
    category: "seafood",
    categoryLabel: categoryLabelMap.seafood,
    name: "Jumbo Gulf Shrimp",
    shortDescription: "16/20 peeled and deveined shrimp for easy dinners.",
    imageUrl: "https://images.unsplash.com/photo-1565680018434-b513d9f7f6f4?auto=format&fit=crop&w=900&q=80",
    tags: ["seafood", "quick-cook"],
    variations: [{ id: "var_shrimp_1lb", name: "1 lb bag", sku: "SEA-SHR-1", priceMoney: { amount: 1699, currency: "USD" }, unitName: "lb" }],
  },
  {
    id: "item_prepared_meatloaf",
    slug: "ready-bake-meatloaf",
    category: "prepared-foods",
    categoryLabel: categoryLabelMap["prepared-foods"],
    name: "Ready-to-Bake Meatloaf",
    shortDescription: "Seasoned meatloaf in oven-safe tray, serves 4.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
    tags: ["family-meal", "oven-ready"],
    variations: [{ id: "var_meatloaf_family", name: "Family tray", sku: "PREP-MEATLOAF-1", priceMoney: { amount: 2199, currency: "USD" }, unitName: "tray" }],
  },
  {
    id: "item_prepared_mac",
    slug: "smoked-gouda-mac",
    category: "prepared-foods",
    categoryLabel: categoryLabelMap["prepared-foods"],
    name: "Smoked Gouda Mac & Cheese",
    shortDescription: "Creamy side dish finished with toasted breadcrumb crust.",
    imageUrl: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["side", "oven-ready"],
    variations: [{ id: "var_mac_32oz", name: "32 oz pan", sku: "PREP-MAC-32", priceMoney: { amount: 1499, currency: "USD" }, unitName: "pan" }],
  },
  {
    id: "item_bundle_weekender",
    slug: "weekend-grill-bundle",
    category: "bundles",
    categoryLabel: categoryLabelMap.bundles,
    name: "Weekend Grill Bundle",
    shortDescription: "Ribeyes, brats, burger patties, and buns for six.",
    imageUrl: "https://images.unsplash.com/photo-1529692236671-f1dc1f55fe80?auto=format&fit=crop&w=900&q=80",
    featured: true,
    tags: ["bundle", "grill", "family-meal"],
    variations: [{ id: "var_bundle_weekend", name: "Bundle", sku: "BUND-WKND-1", priceMoney: { amount: 8999, currency: "USD" }, unitName: "bundle" }],
  },
  {
    id: "item_bundle_freezer",
    slug: "freezer-starter-box",
    category: "bundles",
    categoryLabel: categoryLabelMap.bundles,
    name: "Freezer Starter Box",
    shortDescription: "Assorted steaks, chicken, pork chops, and ground beef.",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
    tags: ["bundle", "meal-prep"],
    variations: [{ id: "var_bundle_freezer", name: "20 lb box", sku: "BUND-FRZR-20", priceMoney: { amount: 15999, currency: "USD" }, unitName: "box" }],
  },
];

export const mockCatalogBrowsePayload: CatalogBrowsePayload = {
  categories: CATEGORY_COPY,
  products: mockCatalogProducts,
  filters: {
    tags: [
      "bundle",
      "family-meal",
      "grill",
      "house-made",
      "meal-prep",
      "oven-ready",
      "party",
      "seafood",
      "weeknight",
    ],
    defaultSort: "featured",
    sortOptions: [
      { value: "featured", label: "Featured" },
      { value: "name", label: "Name (A–Z)" },
      { value: "price-asc", label: "Price: Low to High" },
      { value: "price-desc", label: "Price: High to Low" },
    ],
  },
};
